/**
 * EYARDPRO - Responsive Admin Theme
 *
 */
 (function() {
    'use strict';
function config($translateProvider) {

    $translateProvider.useSanitizeValueStrategy('sanitizeParameters')
        .translations('en', {

            // Define all menu elements
            DASHBOARD: 'Dashboard',
            ASSESSMENT: 'Test',
            LOGOUT: 'Logout',
            CREATE_PROJECT : 'Create Project',
            CREATE_ASSESSMENT:'Create Test',
            INVITE_CANDIDATE:'Invite Candidate',
            PROJECTS:'Projects',
            GRAPHS: 'Graphs',
            MAILBOX: 'Mailbox',
            WIDGETS: 'Widgets',
            METRICS: 'Metrics',
            FORMS: 'Forms',
            APPVIEWS: 'App views',
            OTHERPAGES: 'Other pages',
            UIELEMENTS: 'UI elements',
            MISCELLANEOUS: 'Miscellaneous',
            GRIDOPTIONS: 'Grid options',
            TABLES: 'Tables',
            COMMERCE: 'E-commerce',
            GALLERY: 'Gallery',
            MENULEVELS: 'Menu levels',
            ANIMATIONS: 'Animations',
            LANDING: 'Landing page',
            LAYOUTS: 'Layouts',
            TESTS : 'Tests',

            // Define some custom text
            WELCOME: 'Welcome Amelia',
            MESSAGEINFO: 'You have 42 messages and 6 notifications.',
            SEARCH: 'Search for something...',
            DEMO: 'Internationalization (sometimes shortened to \"I18N , meaning \"I - eighteen letters -N\") is the process of planning and implementing products and services so that they can easily be adapted to specific local languages and cultures, a process called localization . The internationalization process is sometimes called translation or localization enablement .',

            HIREREALCODERS : 'Hire real coders',
            THROUGHTHEAPP : 'through real Application',
            
            LOGIN : 'Log In',
            EMAIL : 'Email',
            PASSWORD : 'Password',
            VALIDEMAIL: 'Please input a valid email address',
            INPUTPASSWORD : 'Please input a password',
            MINLENGTHPASSWORD : 'Your password is required to be at least 6 characters',
            FORGOTPASSWORD : 'Forgot password',
            REGISTERTO : 'Register to',
            CREATEDON : 'Created on',
            INVITED : 'Invited',
            COMPLETED : 'Completed',
            PREVIOUS : 'Previous',
            NEXT : 'Next',
            NOASSESSMENTS : 'No tests found',
            EDIT_ASSESSMENT : 'Edit Test',
            UPDATE_ASSESSMENT : 'Update Test',
            CLONE_ASSESSMENT : 'Clone Test',
            ASSESSMENTNAME : 'Test Name',
            INPUTASSESSMENTNAME : 'Please input a test name',
            MAXASSESSMENTNAME : 'Test name must be less than 256 character',
            VALIDASSESSMENTNAME : 'Test name should be alphanumeric,- & _"',
            PROJECTTYPE : 'Project Type',
            PROJECTLEVEL : 'Project Level',
            TECHNOLOGIES : 'Technologies',
            VALIDTECHNOLOGY : 'Please choose technology',
            LINKEXPIRYTIME : 'Link Validity Time',
            VALIDLINKEXPIRYTIME : 'Please input a valid link validity time',
            MIN : 'Min',
            HRS : 'Hrs',
            PROJECTDURATION : 'Project Duration',
            VALIDDURATION : 'Please input a valid duration',
            NOPROJECTS : 'No Projects Found',
            PROJECTLIST : 'Project List',
            ALLPROJECTS : 'All Projects',
            MYPROJECTS : 'My Projects',
            EYARDPROPROJECTS :'Codeffy Projects',
            EXPECTEDDURATION : 'Expected Duration',
            SELECTEDPROJECTS : 'Selected Projects',
            VALIDSELECTEDPROJECTS : 'Please add the projects',
            ADDPROJECTSHERE : 'Add the projects here',
            INVITECANDIDATE : 'Invite Candidates',
            BATCHFIELDVALIDATION :'Batch field cannot be blank',
            INVITE : 'Invite',
            EMAILTEMPLATE : 'Email Template',
            CONTENTOFEMAIL :'The content for the email',
            SAVEANDPREVIEW : 'Save and Preview',
            EMAILPREVIEW : 'Email Preview',
            CLONEASSESSMENT : 'Clone Test',
            VIEWASSESSMENT : 'View Test',
            LEVEL : 'Level',
            ASSESSMENTDURATION : 'Test Duration',
            ASSESSMENTINVIEDCANIDATES : 'Test Invited Candidates',
            ASSESSMENTCOMPLETEDCANDIDATES : 'Test Completed Candidates',
            ASSESSMENTCREATEDON : 'Test Created On',
            ASSESSMENTUPDATEDON : 'Test Updated On',
            DESCRIPTION : 'Description',
            PROJECTSLIST : 'Projects List',
            DURATION : 'Duration',
            NOOFTIMEPROJECTUSED : 'Number of times project used',
            UPDATEDON : 'Updated On',
            SCROLLDOWNTOLOADMORE : 'Scroll Down To Load More Projects',
            PROJECTNAME: 'Project name',
            CANDIDATESLIST : 'Candidates List',
            NOCANDIDATESFOUND : 'No candidates found',
            CANDIDATENAME : 'Candidate Name',
            CANDIDATEEMAIL : 'Candidate Email',
            ACTION : 'Action',
            PROJECTDETAILS : 'Project Details',
            TITLE : 'Title',
            TYPE : 'Type',
            SUMMERY : 'Summery',
            ESTIMATED_DURATION : 'Estimated Duration',
            EASY : 'Easy',
            MEDIUM : 'Medium',
            HARD : 'Hard',
            NOINSTANCES : 'No instance found',
            INSTANCENAME: 'Instance Name',
            WORKSPACE : 'Workspace',
            INSTANCESTATUS : 'Instance Status',
            PARENTUSERNAME : 'Parent User Name',
            PARENTUSEREMAIL : 'Parent User Email',
            PARENTUSERACCESSED : 'Parent User Last Accessed',
            USERNAME : 'User name',
            USEREMAIL : 'User email',
            STATUS : 'Status',
            NOUSERSFOUND : 'No users found',
            ROLE:'Role',
            USERINFO : 'User Info',
            ADDNEWUSER : 'Add New User',
            ROLEINFO : 'Role Info',
            MYDETAILS : 'Personal Information',
            EVALUATORS : 'Evaluators',
            TECHNOLOGY : 'Technology',
            DEACTIVATEDPROJECTS: 'Deactivated Projects',
            TIMEZONE : 'Timezone',
            ACTIVITY : 'Activity',
            SETTINGS : 'Settings',
            CHANGEPASSWORD : 'Change Password',
            CURRENTPASSWORD : 'Current Password',
            NEWPASSWORD : 'New Password',
            CONFIRMPASSWORD : 'Confirm Password',
            ACTIVE : 'Active',
            DEACTIVE : 'Deactived',
            USERS : 'Users',
            CANDIDATEREGISTRATIONFIELDS : 'Candidate Registration Fields',
            COMPANYINFORMATION : 'Company Information',
            COMPANYNAME : 'Company Name',
            COMPANYWEBSITE : 'Company Website',
            COMPANYADDRESS : 'Company Address',
            EyardstickPro : 'Codeffy',
            NAME : 'Name',
            FULLNAME : 'Full Name',
            ADDRESS : 'Address',
            JOBTITLE : 'Job Title',
            CONTACTNUMBER : 'Contact Number',
            COUNTRY : 'Country',
            SONAR_REPORT:'Sonar Report',
            TESTS_CREATED:'Tests Created',
            CANDIDATE_INVITED:'Candidate Invited',
            CANDIDATE_PARTICIPATED:'Candidate Participated',
            PROBLEMS:'Problems',
            PROBLEMS_CREATED:'Problems Created',
            PROBLEMS_USED:'Problems Used',
            CREATE_PROBLEM:'Create Problem',
            STACKS_USAGE:'Stacks Usage',
            CREATE_NEW_INSTANCE:'Create New Instance',
            REGISTERING:'registering',
            PASSWORD_NOT_MATCH:'Password and Confirm Password did not match.'
        })
        .translations('es', {

            // Define all menu elements
            DASHBOARD: 'Salpicadero',
            ASSESSMENT: 'మూల్యాంకనం',
            LOGOUT:'నిష్క్రమణ',
            CREATE_PROJECT: 'Crear proyecto',
            CREATE_ASSESSMENT:'Crear evaluación',
            INVITE_CANDIDATE:'Invite Candidate',
            PROJECTS : 'ప్రాజెక్టు',
            GRAPHS: 'Gráficos',
            MAILBOX: 'El correo',
            WIDGETS: 'Widgets',
            METRICS: 'Métrica',
            FORMS: 'Formas',
            APPVIEWS: 'Vistas app',
            OTHERPAGES: 'Otras páginas',
            UIELEMENTS: 'UI elements',
            MISCELLANEOUS: 'Misceláneo',
            GRIDOPTIONS: 'Cuadrícula',
            TABLES: 'Tablas',
            COMMERCE: 'E-comercio',
            GALLERY: 'Galería',
            MENULEVELS: 'Niveles de menú',
            ANIMATIONS: 'Animaciones',
            LANDING: 'Página de destino',
            LAYOUTS: 'Esquemas',

            // Define some custom text
            WELCOME: 'Bienvenido Amelia',
            MESSAGEINFO: 'Usted tiene 42 mensajes y 6 notificaciones.',
            SEARCH: 'Busca algo ...',
            DEMO: 'Internacionalización (a veces abreviado como \"I18N, que significa\" I - dieciocho letras N \") es el proceso de planificación e implementación de productos y servicios de manera que se pueden adaptar fácilmente a las lenguas y culturas locales específicas, un proceso llamado localización El proceso de internacionalización. a veces se llama la traducción o la habilitación de localización.',

            HIREREALCODERS : 'Hire real coders',
            THROUGHTHEAPP : 'through real Application',
            LOGIN : 'లాగిన్',
            EMAIL : 'ఇమెయిల్',
            PASSWORD : 'పాస్వర్డ్',
            VALIDEMAIL: 'ఇన్పుట్ చెల్లుబాటు అయ్యే ఇమెయిల్ చిరునామా ప్లీజ్',
            INPUTPASSWORD : 'ఇన్పుట్ పాస్వర్డ్ను ప్లీజ్',
            MINLENGTHPASSWORD :'మీ పాస్వర్డ్ను కనీసం 6 అక్షరాల అవసరం',
            FORGOTPASSWORD : 'పాస్వర్డ్ మరిచిపోయారా',
            REGISTERTO : 'కు నమోదు',
            CREATEDON : 'రూపొందించబడింది',
            INVITED : 'ఆహ్వానించబడినవి',
            COMPLETED : 'పూర్తి',
            PREVIOUS :'మునుపటి',
            NEXT: 'తరువాత',
            NOASSESSMENTS : 'తోబుట్టువుల లెక్కింపులు దొరకలేదు',
            EDIT_ASSESSMENT : 'Edit Test',
            UPDATE_ASSESSMENT : 'Update Test',
            CLONE_ASSESSMENT : 'Clone Test',
            ASSESSMENTNAME : 'Test Name',
            INPUTASSESSMENTNAME : 'Please input a assessment name',
            MAXASSESSMENTNAME : 'Test name must be less than 256 character',
            VALIDASSESSMENTNAME : 'Test name should be alphanumeric,- & _"',
            PROJECTTYPE : 'Project Type',
            PROJECTLEVEL : 'Project Level',
            TECHNOLOGIES : 'Technologies',
            VALIDTECHNOLOGY : 'Please choose technology',
            LINKEXPIRYTIME : 'Link Validity Time',
            VALIDLINKEXPIRYTIME : 'Please input a valid link validity time',
            MIN : 'Min',
            HRS : 'Hrs',
            PROJECTDURATION : 'Project Duration',
            VALIDDURATION : 'Please input a valid duration',
            NOPROJECTS : 'No Projects Found',
            PROJECTLIST : 'Project List',
            ALLPROJECTS : 'All Projects',
            MYPROJECTS : 'My Projects',
            EYARDPROPROJECTS :'Codeffy Projects',
            EXPECTEDDURATION : 'Expected Duration',
            SELECTEDPROJECTS : 'Selected Projects',
            VALIDSELECTEDPROJECTS : 'Please add the projects',
            ADDPROJECTSHERE : 'Add the projects here',
            INVITECANDIDATE : 'Invite Candidates',
            BATCHFIELDVALIDATION :'Batch field cannot be blank',
            INVITE : 'Invite',
            EMAILTEMPLATE : 'Email Template',
            CONTENTOFEMAIL :'The content for the email',
            SAVEANDPREVIEW : 'Save and Preview',
            CLONEASSESSMENT : 'Clone Test',
            VIEWASSESSMENT : 'View Test',
            LEVEL : 'Level',
            ASSESSMENTDURATION : 'Test Duration',
            ASSESSMENTINVIEDCANIDATES : 'Test Invited Candidates',
            ASSESSMENTCOMPLETEDCANDIDATES : 'Test Completed Candidates',
            ASSESSMENTCREATEDON : 'Test Created On',
            ASSESSMENTUPDATEDON : 'Test Updated On',
            DESCRIPTION : 'Description',
            PROJECTSLIST : 'Projects List',
            DURATION : 'Duration',
            NOOFTIMEPROJECTUSED : 'Number of times project used',
            UPDATEDON : 'Updated On',
            SCROLLDOWNTOLOADMORE : 'Scroll Down To Load More Projects',
            PROJECTNAME: 'Project name',
            CANDIDATESLIST : 'Candidates List',
            NOCANDIDATESFOUND : 'No candidates found',
            CANDIDATENAME : 'Candidate Name',
            CANDIDATEEMAIL : 'Candidate Email',
            ACTION : 'Action',
            PROJECTDETAILS : 'Project Details',
            TITLE : 'Title',
            TYPE : 'Type',
            SUMMERY : 'Summery',
            ESTIMATED_DURATION : 'Estimated Duration',
            EASY : 'Easy',
            MEDIUM : 'Medium',
            HARD : 'Hard',
            NOINSTANCES : 'No instance found',
            INSTANCENAME: 'Instance Name',
            WORKSPACE : 'Workspace',
            INSTANCESTATUS : 'Instance Status',
            PARENTUSERNAME : 'Parent User Name',
            PARENTUSEREMAIL : 'Parent User Email',
            PARENTUSERACCESSED : 'Parent User Last Accessed',
            USERNAME : 'User name',
            USEREMAIL : 'User email',
            STATUS : 'Status',
            NOUSERSFOUND : 'No users found',
            USERINFO : 'User Info',
            ADDNEWUSER : 'Add New User',
            ROLE : 'Role',
            ROLEINFO : 'Role Info',
            MYDETAILS : 'Personal Information',
            EVALUATORS : 'Evaluators',
            TECHNOLOGY : 'Technology',
            DEACTIVATEDPROJECTS: 'Deactivated Projects',
            TIMEZONE : 'Timezone',
            ACTIVITY : 'Activity',
            CHANGEPASSWORD : 'Change Password',
            CURRENTPASSWORD : 'Current Password',
            NEWPASSWORD : 'New Password',
            CONFIRMPASSWORD : 'Confirm Password',
            ACTIVE : 'Active',
            DEACTIVE : 'Deactive',
            USERS : 'Users',
            CANDIDATEREGISTRATIONFIELDS : 'Candidate Registration Fields',
            COMPANYINFORMATION : 'Company Information',
            COMPANYNAME : 'Company Name',
            COMPANYWEBSITE : 'Company Website',
            COMPANYADDRESS : 'Company Address',
            EyardstickPro : 'Codeffy',
            NAME : 'Name',
            FULLNAME : 'Full Name',
            ADDRESS : 'Address',
            JOBTITLE : 'Job Title',
            CONTACTNUMBER : 'Contact Number',
            COUNTRY : 'Country',
            TESTS : 'Tests',
            SONAR_REPORT:'Sonar Report',
            TESTS_CREATED:'Tests Created',
            CANDIDATE_INVITED:'Candidate Invited',
            CANDIDATE_PARTICIPATED:'Candidate Participated',
            PROBLEMS:'Problems',
            PROBLEMS_CREATED:'Problems Created',
            PROBLEMS_USED:'Problems Used',
            CREATE_PROBLEM:'Create Problem',
            STACKS_USAGE:'Stacks Usage',
            CREATE_NEW_INSTANCE:'Create New Instance',
            REGISTERING:'registering',
            PASSWORD_NOT_MATCH:'Password and Confirm Password did not match.'

        });
    $translateProvider.preferredLanguage('en');
}

angular
    .module('angularSeedApp')
    .config(config);
})();